# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-31 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=20)),
                ('parameters', models.CharField(max_length=300)),
                ('startTime', models.DateField()),
            ],
        ),
    ]
